"""menstrual cycle details

Revision ID: d8a0bc9afdd9
Revises: 6b11080054a0

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d8a0bc9afdd9"
down_revision: Union[str, None] = "6b11080054a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menstrual_cycle_details",
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("day_in_cycle", sa.Integer(), nullable=True),
        sa.Column("current_phase", sa.Integer(), nullable=True),
        sa.Column("current_phase_type", sa.String(length=32), nullable=True),
        sa.Column("length_of_current_phase", sa.Integer(), nullable=True),
        sa.Column("days_until_next_phase", sa.Integer(), nullable=True),
        sa.Column("predicted_cycle_length", sa.Integer(), nullable=True),
        sa.Column("is_predicted_cycle", sa.Boolean(), nullable=True),
        sa.Column("cycle_length", sa.Integer(), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("has_specified_cycle_length", sa.Boolean(), nullable=True),
        sa.Column("has_specified_period_length", sa.Boolean(), nullable=True),
        sa.Column("period_length", sa.Integer(), nullable=True),
        sa.Column("fertile_window_start", sa.Integer(), nullable=True),
        sa.Column("length_of_fertile_window", sa.Integer(), nullable=True),
        sa.Column("pregnancy_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["record_id"], ["event_record_detail.record_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("record_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("menstrual_cycle_details")
    # ### end Alembic commands ###
